export const CREATE_POST = 'rrs/post/CREATE_POST'
export const FETCH_POSTS = 'rrs/post/FETCH_POSTS'
export const REQUEST_POSTS = 'rrs/post/REQUEST_POSTS'
export const SHOW_LOADER = 'rrs/app/SHOW_LOADER'
export const HIDE_LOADER = 'rrs/app/HIDE_LOADER'
export const SHOW_ALERT = 'rrs/app/SHOW_ALERT'
export const HIDE_ALERT = 'rrs/app/HIDE_ALERT'
